### PR TITLE
Deployments/iac

### PR DESCRIPTION
**Pull request by waleedkm**
Workflows was set up to automate image upload to docker registry

### CODE REVIEW

**Comment by waleedkm** [comment]
verified to merge

**Comment by waleedkm** [comment]
Ok

**Comment by JasirBasheer** [comment]
i have merged the pull request to the main branch
everything is working properly as expected

so i did not got any idea on what is exactly happening
if you can. can you please teach me how this things works
it should be great . if you are free
maybe in a google meet or something?

**Comment by waleedkm** [comment]
Dear Jasir
We can have a meeting now if you are available
https://meet.google.com/ewu-eyed-eod

Waleed K  M
DevOps | Cloud | IT Support
Contact No: India  - +919995102181
           UAE   - +971563590830 
Find me on LinkedIn<https://ie.linkedin.com/in/waleedkm60>
________________________________

**Comment by JasirBasheer** [comment]
I’m really sorry for The delay, I was in the middle of review . if you’re
free, we can have a meeting now

**Pull request merged**
